"""Public exports for the Christian virtue SFT dataset, runtime, evaluation, and publication API."""

from .builders import BenchmarkExample, BuiltDataset, SFTExample, build_dataset
from .chat import (
    DEFAULT_CHAT_OUTPUT_ROOT,
    DEFAULT_CHAT_SYSTEM_PROMPT,
    ChatModelBundle,
    LiveChatSession,
    chat_session_paths,
    create_live_chat_session,
    describe_chat_plan,
    generate_chat_reply,
    generate_deterministic_chat_reply,
    load_chat_model_bundle,
    persist_live_chat_session,
    record_chat_exchange,
    record_chat_reset,
    render_chat_transcript_markdown,
    run_interactive_chat,
)
from .chat_smoke import (
    DEFAULT_CHAT_EXAMPLE_PROMPTS,
    DEFAULT_CHAT_SMOKE_OUTPUT_ROOT,
    ChatSmokeCase,
    ChatSmokeCaseResult,
    evaluate_chat_smoke_case,
    render_chat_smoke_report,
    run_chat_smoke_suite,
)
from .comparison import build_comparison_report, load_metrics_file, write_comparison_report
from .config import (
    DatasetBuildConfig,
    InferenceConfig,
    TrainingConfig,
    load_dataset_build_config,
    load_inference_config,
    load_training_config,
)
from .doc_links import extract_markdown_targets, resolve_internal_markdown_target
from .evaluation import evaluate_predictions, write_markdown_report, write_metrics_json
from .inference import describe_inference_plan, load_benchmark_inputs, run_generation_inference
from .preflight import (
    missing_required_paths,
    module_import_status,
    python_version_ok,
    python_version_string,
    workspace_free_gb,
    writable_directory_status,
)
from .public_artifacts import (
    DEFAULT_PUBLICATION_PACKAGE_MANIFEST,
    build_publication_doc_expectations,
    verify_publication_bundle,
)
from .publication import (
    build_adapter_package_manifest,
    build_model_card_text,
    build_release_notes_text,
    create_or_update_github_release,
    default_release_target,
    publish_adapter_package_to_hf,
    release_target_from_train_run,
    write_adapter_package,
)
from .reporting import (
    build_goal_demo_panel,
    build_publishable_local_report,
    write_publishable_local_report,
    write_task_comparison_svg,
    write_training_curves_svg,
)
from .run_layout import (
    build_environment_snapshot,
    create_timestamped_run_dir,
    current_git_commit,
    dataset_manifest_path,
    default_evaluation_paths,
    generate_run_id,
    iso_timestamp,
    run_artifacts_for_dir,
    write_config_snapshot,
    write_json,
    write_jsonl,
)
from .runtime import detect_torch_availability, resolve_model_runtime
from .serialization import serialize_built_dataset
from .training import describe_training_plan, resolve_training_runtime, run_qlora_training

__all__ = [
    "BenchmarkExample",
    "BuiltDataset",
    "ChatSmokeCase",
    "ChatSmokeCaseResult",
    "DEFAULT_CHAT_EXAMPLE_PROMPTS",
    "DEFAULT_CHAT_OUTPUT_ROOT",
    "DEFAULT_CHAT_SMOKE_OUTPUT_ROOT",
    "DEFAULT_CHAT_SYSTEM_PROMPT",
    "ChatModelBundle",
    "DatasetBuildConfig",
    "InferenceConfig",
    "LiveChatSession",
    "SFTExample",
    "TrainingConfig",
    "build_adapter_package_manifest",
    "build_comparison_report",
    "build_goal_demo_panel",
    "build_model_card_text",
    "build_publishable_local_report",
    "build_release_notes_text",
    "build_environment_snapshot",
    "build_dataset",
    "create_or_update_github_release",
    "create_live_chat_session",
    "create_timestamped_run_dir",
    "current_git_commit",
    "chat_session_paths",
    "dataset_manifest_path",
    "DEFAULT_PUBLICATION_PACKAGE_MANIFEST",
    "default_release_target",
    "detect_torch_availability",
    "describe_chat_plan",
    "describe_inference_plan",
    "describe_training_plan",
    "default_evaluation_paths",
    "evaluate_predictions",
    "evaluate_chat_smoke_case",
    "extract_markdown_targets",
    "generate_run_id",
    "generate_chat_reply",
    "generate_deterministic_chat_reply",
    "iso_timestamp",
    "load_benchmark_inputs",
    "load_dataset_build_config",
    "load_chat_model_bundle",
    "load_metrics_file",
    "load_inference_config",
    "load_training_config",
    "missing_required_paths",
    "module_import_status",
    "python_version_ok",
    "python_version_string",
    "publish_adapter_package_to_hf",
    "persist_live_chat_session",
    "record_chat_exchange",
    "record_chat_reset",
    "release_target_from_train_run",
    "resolve_internal_markdown_target",
    "resolve_model_runtime",
    "resolve_training_runtime",
    "run_artifacts_for_dir",
    "run_chat_smoke_suite",
    "run_generation_inference",
    "run_interactive_chat",
    "run_qlora_training",
    "render_chat_smoke_report",
    "render_chat_transcript_markdown",
    "serialize_built_dataset",
    "build_publication_doc_expectations",
    "verify_publication_bundle",
    "workspace_free_gb",
    "writable_directory_status",
    "write_adapter_package",
    "write_comparison_report",
    "write_config_snapshot",
    "write_json",
    "write_jsonl",
    "write_markdown_report",
    "write_metrics_json",
    "write_publishable_local_report",
    "write_task_comparison_svg",
    "write_training_curves_svg",
]
