from __future__ import annotations

from ..models.pilot import PilotRelationType

EXTRA_CORPUS_CONCEPTS = [
    {
        "concept_id": "concept.hope",
        "canonical_label": "Hope",
        "node_type": "virtue",
        "aliases": ["hope"],
        "description": "The theological virtue by which eternal beatitude is expected from God.",
        "notes": [],
        "parent_concept_id": "concept.theological_virtue",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.faith", "concept.charity"],
        "introduced_in_questions": ["st.ii-ii.q017"],
    },
    {
        "concept_id": "concept.fortitude",
        "canonical_label": "Fortitude",
        "node_type": "virtue",
        "aliases": ["fortitude"],
        "description": "The cardinal virtue governing firmness in difficulties and dangers.",
        "notes": [],
        "parent_concept_id": "concept.cardinal_virtue",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.cowardice"],
        "introduced_in_questions": ["st.ii-ii.q123"],
    },
    {
        "concept_id": "concept.temperance",
        "canonical_label": "Temperance",
        "node_type": "virtue",
        "aliases": ["temperance"],
        "description": "The cardinal virtue moderating attractions of pleasure.",
        "notes": [],
        "parent_concept_id": "concept.cardinal_virtue",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.intemperance"],
        "introduced_in_questions": ["st.ii-ii.q141"],
    },
    {
        "concept_id": "concept.theological_virtue",
        "canonical_label": "Theological Virtue",
        "node_type": "virtue",
        "aliases": ["theological virtue", "theological virtues"],
        "description": "Virtue having God as its immediate object.",
        "notes": [],
        "parent_concept_id": None,
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.faith", "concept.hope", "concept.charity"],
        "introduced_in_questions": ["st.i-ii.q062"],
    },
    {
        "concept_id": "concept.cardinal_virtue",
        "canonical_label": "Cardinal Virtue",
        "node_type": "virtue",
        "aliases": ["cardinal virtue", "cardinal virtues"],
        "description": "Principal moral virtue around which others are ordered.",
        "notes": [],
        "parent_concept_id": None,
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": [
            "concept.prudence",
            "concept.justice",
            "concept.fortitude",
            "concept.temperance",
        ],
        "introduced_in_questions": ["st.i-ii.q061"],
    },
    {
        "concept_id": "concept.wisdom_gift",
        "canonical_label": "Gift of Wisdom",
        "node_type": "gift_holy_spirit",
        "aliases": ["gift of wisdom"],
        "description": "Gift of the Holy Spirit perfecting higher judgment by divine things.",
        "notes": [],
        "parent_concept_id": "concept.gift_holy_spirit",
        "registry_status": "seed",
        "disambiguation_notes": ["Keep distinct from wisdom as an acquired or infused virtue."],
        "related_concepts": ["concept.beatitude", "concept.charity"],
        "introduced_in_questions": ["st.ii-ii.q045"],
    },
    {
        "concept_id": "concept.understanding_gift",
        "canonical_label": "Gift of Understanding",
        "node_type": "gift_holy_spirit",
        "aliases": ["gift of understanding"],
        "description": "Gift of the Holy Spirit granting penetration into divine truth.",
        "notes": [],
        "parent_concept_id": "concept.gift_holy_spirit",
        "registry_status": "seed",
        "disambiguation_notes": ["Keep distinct from prudence-part intelligence or understanding."],
        "related_concepts": ["concept.faith"],
        "introduced_in_questions": ["st.ii-ii.q008"],
    },
    {
        "concept_id": "concept.counsel_gift",
        "canonical_label": "Gift of Counsel",
        "node_type": "gift_holy_spirit",
        "aliases": ["gift of counsel"],
        "description": "Gift of the Holy Spirit perfecting right counsel in action.",
        "notes": [],
        "parent_concept_id": "concept.gift_holy_spirit",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.prudence"],
        "introduced_in_questions": ["st.ii-ii.q052"],
    },
    {
        "concept_id": "concept.fortitude_gift",
        "canonical_label": "Gift of Fortitude",
        "node_type": "gift_holy_spirit",
        "aliases": ["gift of fortitude"],
        "description": "Gift of the Holy Spirit strengthening endurance in arduous good.",
        "notes": [],
        "parent_concept_id": "concept.gift_holy_spirit",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.fortitude"],
        "introduced_in_questions": ["st.ii-ii.q139"],
    },
    {
        "concept_id": "concept.knowledge_gift",
        "canonical_label": "Gift of Knowledge",
        "node_type": "gift_holy_spirit",
        "aliases": ["gift of knowledge"],
        "description": "Gift of the Holy Spirit for judging created things in relation to God.",
        "notes": [],
        "parent_concept_id": "concept.gift_holy_spirit",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.faith"],
        "introduced_in_questions": ["st.ii-ii.q009"],
    },
    {
        "concept_id": "concept.piety_gift",
        "canonical_label": "Gift of Piety",
        "node_type": "gift_holy_spirit",
        "aliases": ["gift of piety"],
        "description": "Gift of the Holy Spirit inclining filial reverence toward God.",
        "notes": [],
        "parent_concept_id": "concept.gift_holy_spirit",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.justice"],
        "introduced_in_questions": ["st.ii-ii.q121"],
    },
    {
        "concept_id": "concept.fear_of_lord_gift",
        "canonical_label": "Gift of Fear of the Lord",
        "node_type": "gift_holy_spirit",
        "aliases": ["fear of the Lord", "gift of fear of the Lord"],
        "description": "Gift of the Holy Spirit producing reverential fear before God.",
        "notes": [],
        "parent_concept_id": "concept.gift_holy_spirit",
        "registry_status": "seed",
        "disambiguation_notes": ["Keep distinct from passion-level fear."],
        "related_concepts": ["concept.fear"],
        "introduced_in_questions": ["st.ii-ii.q019"],
    },
    {
        "concept_id": "concept.decalogue",
        "canonical_label": "Decalogue",
        "node_type": "precept",
        "aliases": ["decalogue", "ten commandments"],
        "description": "The principal set of precepts delivered in the Old Law.",
        "notes": [],
        "parent_concept_id": "concept.precept",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.commandments"],
        "introduced_in_questions": ["st.i-ii.q100"],
    },
    {
        "concept_id": "concept.new_law_precepts",
        "canonical_label": "Precepts of the New Law",
        "node_type": "precept",
        "aliases": ["precepts of the new law", "new law precepts"],
        "description": "Precepts specifically belonging to the New Law.",
        "notes": [],
        "parent_concept_id": "concept.precept",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.divine_law"],
        "introduced_in_questions": ["st.i-ii.q108"],
    },
    {
        "concept_id": "concept.imprudence",
        "canonical_label": "Imprudence",
        "node_type": "vice",
        "aliases": ["imprudence"],
        "description": "Vice opposed to prudence.",
        "notes": [],
        "parent_concept_id": "concept.vice",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.prudence"],
        "introduced_in_questions": ["st.ii-ii.q053"],
    },
    {
        "concept_id": "concept.injustice",
        "canonical_label": "Injustice",
        "node_type": "vice",
        "aliases": ["injustice"],
        "description": "Vice opposed to justice.",
        "notes": [],
        "parent_concept_id": "concept.vice",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.justice"],
        "introduced_in_questions": ["st.ii-ii.q059"],
    },
    {
        "concept_id": "concept.intemperance",
        "canonical_label": "Intemperance",
        "node_type": "vice",
        "aliases": ["intemperance"],
        "description": "Vice opposed to temperance.",
        "notes": [],
        "parent_concept_id": "concept.vice",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.temperance"],
        "introduced_in_questions": ["st.ii-ii.q142"],
    },
    {
        "concept_id": "concept.cowardice",
        "canonical_label": "Cowardice",
        "node_type": "vice",
        "aliases": ["cowardice"],
        "description": "Vice opposed to fortitude.",
        "notes": [],
        "parent_concept_id": "concept.vice",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.fortitude"],
        "introduced_in_questions": ["st.ii-ii.q125"],
    },
    {
        "concept_id": "concept.beatitude_poor_in_spirit",
        "canonical_label": "Beatitude of the Poor in Spirit",
        "node_type": "beatitude",
        "aliases": ["poor in spirit"],
        "description": "Beatitude pronounced on the poor in spirit.",
        "notes": [],
        "parent_concept_id": "concept.beatitude",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.beatitude"],
        "introduced_in_questions": ["st.i-ii.q069"],
    },
    {
        "concept_id": "concept.beatitude_meek",
        "canonical_label": "Beatitude of the Meek",
        "node_type": "beatitude",
        "aliases": ["the meek", "meek"],
        "description": "Beatitude pronounced on the meek.",
        "notes": [],
        "parent_concept_id": "concept.beatitude",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.beatitude"],
        "introduced_in_questions": ["st.i-ii.q069"],
    },
    {
        "concept_id": "concept.beatitude_mourn",
        "canonical_label": "Beatitude of Those Who Mourn",
        "node_type": "beatitude",
        "aliases": ["they that mourn", "those who mourn"],
        "description": "Beatitude pronounced on those who mourn.",
        "notes": [],
        "parent_concept_id": "concept.beatitude",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.beatitude"],
        "introduced_in_questions": ["st.i-ii.q069"],
    },
    {
        "concept_id": "concept.beatitude_hunger_for_justice",
        "canonical_label": "Beatitude of Hunger and Thirst for Justice",
        "node_type": "beatitude",
        "aliases": [
            "hunger and thirst after justice",
            "those who hunger and thirst for justice",
        ],
        "description": "Beatitude pronounced on those hungering and thirsting for justice.",
        "notes": [],
        "parent_concept_id": "concept.beatitude",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.justice"],
        "introduced_in_questions": ["st.i-ii.q069"],
    },
    {
        "concept_id": "concept.beatitude_merciful",
        "canonical_label": "Beatitude of the Merciful",
        "node_type": "beatitude",
        "aliases": ["the merciful", "merciful"],
        "description": "Beatitude pronounced on the merciful.",
        "notes": [],
        "parent_concept_id": "concept.beatitude",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.beatitude"],
        "introduced_in_questions": ["st.i-ii.q069"],
    },
    {
        "concept_id": "concept.beatitude_clean_of_heart",
        "canonical_label": "Beatitude of the Clean of Heart",
        "node_type": "beatitude",
        "aliases": ["clean of heart", "pure in heart"],
        "description": "Beatitude pronounced on the clean of heart.",
        "notes": [],
        "parent_concept_id": "concept.beatitude",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.beatitude"],
        "introduced_in_questions": ["st.i-ii.q069"],
    },
    {
        "concept_id": "concept.beatitude_peacemakers",
        "canonical_label": "Beatitude of the Peacemakers",
        "node_type": "beatitude",
        "aliases": ["peacemakers"],
        "description": "Beatitude pronounced on the peacemakers.",
        "notes": [],
        "parent_concept_id": "concept.beatitude",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.beatitude"],
        "introduced_in_questions": ["st.i-ii.q069"],
    },
    {
        "concept_id": "concept.beatitude_persecuted_for_justice",
        "canonical_label": "Beatitude of Those Persecuted for Justice",
        "node_type": "beatitude",
        "aliases": ["persecuted for justice' sake", "persecuted for justice sake"],
        "description": "Beatitude pronounced on those persecuted for justice.",
        "notes": [],
        "parent_concept_id": "concept.beatitude",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.justice"],
        "introduced_in_questions": ["st.i-ii.q069"],
    },
    {
        "concept_id": "concept.act_of_faith",
        "canonical_label": "Act of Faith",
        "node_type": "act_type",
        "aliases": ["act of faith"],
        "description": "The inward believing act by which the intellect assents to divine truth.",
        "notes": [],
        "parent_concept_id": None,
        "registry_status": "seed",
        "disambiguation_notes": ["Keep distinct from the virtue of faith itself."],
        "related_concepts": ["concept.faith", "concept.confession_of_faith"],
        "introduced_in_questions": ["st.ii-ii.q002"],
    },
    {
        "concept_id": "concept.confession_of_faith",
        "canonical_label": "Confession of Faith",
        "node_type": "act_type",
        "aliases": ["confession of faith"],
        "description": "The outward verbal confession of what is held by faith.",
        "notes": [],
        "parent_concept_id": None,
        "registry_status": "seed",
        "disambiguation_notes": ["Keep distinct from the symbol or creed as a textual formula."],
        "related_concepts": ["concept.faith", "concept.symbol_of_faith"],
        "introduced_in_questions": ["st.ii-ii.q003"],
    },
    {
        "concept_id": "concept.unbelief",
        "canonical_label": "Unbelief",
        "node_type": "sin_type",
        "aliases": ["unbelief"],
        "description": "Sin opposed to faith by refusing or despising what faith proposes.",
        "notes": [],
        "parent_concept_id": "concept.sin",
        "registry_status": "seed",
        "disambiguation_notes": ["Keep distinct from mere negative ignorance where the faith has not been heard."],
        "related_concepts": ["concept.faith", "concept.heresy", "concept.apostasy"],
        "introduced_in_questions": ["st.ii-ii.q010"],
    },
    {
        "concept_id": "concept.heresy",
        "canonical_label": "Heresy",
        "node_type": "sin_type",
        "aliases": ["heresy", "heretical misrepresentations"],
        "description": "Species of unbelief choosing private judgment against Christian doctrine.",
        "notes": [],
        "parent_concept_id": "concept.unbelief",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.faith", "concept.unbelief"],
        "introduced_in_questions": ["st.ii-ii.q011"],
    },
    {
        "concept_id": "concept.apostasy",
        "canonical_label": "Apostasy",
        "node_type": "sin_type",
        "aliases": ["apostasy"],
        "description": "Backsliding from God, and absolutely speaking, withdrawal from the faith.",
        "notes": [],
        "parent_concept_id": "concept.unbelief",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.faith", "concept.unbelief"],
        "introduced_in_questions": ["st.ii-ii.q012"],
    },
    {
        "concept_id": "concept.blasphemy",
        "canonical_label": "Blasphemy",
        "node_type": "sin_type",
        "aliases": ["blasphemy"],
        "description": "Disparagement of divine goodness by denying what befits God or affirming what does not.",
        "notes": [],
        "parent_concept_id": "concept.sin",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.confession_of_faith", "concept.faith"],
        "introduced_in_questions": ["st.ii-ii.q013"],
    },
    {
        "concept_id": "concept.blasphemy_against_holy_spirit",
        "canonical_label": "Sin Against the Holy Spirit",
        "node_type": "sin_type",
        "aliases": ["sin against the holy ghost", "sin against the holy spirit"],
        "description": "The special sin against the Holy Spirit as treated in questions 14-15.",
        "notes": [],
        "parent_concept_id": "concept.sin",
        "registry_status": "seed",
        "disambiguation_notes": ["Do not silently merge this with ordinary blasphemy."],
        "related_concepts": ["concept.blasphemy", "concept.despair_sin", "concept.presumption"],
        "introduced_in_questions": ["st.ii-ii.q014", "st.ii-ii.q015"],
    },
    {
        "concept_id": "concept.blindness_of_mind",
        "canonical_label": "Blindness of Mind",
        "node_type": "sin_type",
        "aliases": ["blindness of mind"],
        "description": "Privation of intellectual sight by willful turning away from intelligible principle.",
        "notes": [],
        "parent_concept_id": "concept.blasphemy_against_holy_spirit",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.understanding_gift"],
        "introduced_in_questions": ["st.ii-ii.q015"],
    },
    {
        "concept_id": "concept.dullness_of_sense",
        "canonical_label": "Dullness of Sense",
        "node_type": "sin_type",
        "aliases": ["dullness of sense", "dulness of sense"],
        "description": "Obtuseness of intellectual penetration in spiritual matters.",
        "notes": [],
        "parent_concept_id": "concept.blasphemy_against_holy_spirit",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.understanding_gift"],
        "introduced_in_questions": ["st.ii-ii.q015"],
    },
    {
        "concept_id": "concept.precepts_of_faith_knowledge_and_understanding",
        "canonical_label": "Precepts of Faith, Knowledge, and Understanding",
        "node_type": "precept",
        "aliases": ["precepts of faith", "precepts of faith knowledge and understanding"],
        "description": "Precept material governing faith together with the connected gifts of knowledge and understanding.",
        "notes": [],
        "parent_concept_id": "concept.precept",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.faith", "concept.understanding_gift", "concept.knowledge_gift"],
        "introduced_in_questions": ["st.ii-ii.q016"],
    },
    {
        "concept_id": "concept.despair_sin",
        "canonical_label": "Despair (Sin)",
        "node_type": "sin_type",
        "aliases": ["despair"],
        "description": "Sinful movement contrary to hope by judging pardon or salvation unavailable from God.",
        "notes": [],
        "parent_concept_id": "concept.sin",
        "registry_status": "seed",
        "disambiguation_notes": ["Keep distinct from despair as a passion in the Prima Secundae."],
        "related_concepts": ["concept.hope", "concept.blasphemy_against_holy_spirit"],
        "introduced_in_questions": ["st.ii-ii.q020"],
    },
    {
        "concept_id": "concept.presumption",
        "canonical_label": "Presumption",
        "node_type": "sin_type",
        "aliases": ["presumption"],
        "description": "Immoderate hope relying on God or self in a disordered way.",
        "notes": [],
        "parent_concept_id": "concept.sin",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.hope", "concept.blasphemy_against_holy_spirit"],
        "introduced_in_questions": ["st.ii-ii.q021"],
    },
    {
        "concept_id": "concept.precepts_of_hope_and_fear",
        "canonical_label": "Precepts of Hope and Fear",
        "node_type": "precept",
        "aliases": ["precepts of hope and fear", "precepts of hope"],
        "description": "Precepts or legal preambles ordering the acts of hope and fear.",
        "notes": [],
        "parent_concept_id": "concept.precept",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.hope", "concept.fear_of_lord_gift"],
        "introduced_in_questions": ["st.ii-ii.q022"],
    },
    {
        "concept_id": "concept.love_act",
        "canonical_label": "Love (Act)",
        "node_type": "act_type",
        "aliases": ["act of love", "to love"],
        "description": "The principal act belonging to charity inasmuch as charity loves.",
        "notes": [],
        "parent_concept_id": None,
        "registry_status": "seed",
        "disambiguation_notes": ["Keep distinct from charity as virtue and from love as passion."],
        "related_concepts": ["concept.charity", "concept.love_passion", "concept.hatred_sin"],
        "introduced_in_questions": ["st.ii-ii.q027"],
    },
    {
        "concept_id": "concept.god",
        "canonical_label": "God",
        "node_type": "object",
        "aliases": ["god", "divine good"],
        "description": "God as the object or term of theological virtue and charity.",
        "notes": [],
        "parent_concept_id": None,
        "registry_status": "seed",
        "disambiguation_notes": ["Extremely broad label; do not auto-resolve generic God language into narrow doctrinal claims."],
        "related_concepts": ["concept.faith", "concept.hope", "concept.charity"],
        "introduced_in_questions": ["st.ii-ii.q001", "st.ii-ii.q017", "st.ii-ii.q023"],
    },
    {
        "concept_id": "concept.neighbor",
        "canonical_label": "Neighbor",
        "node_type": "object",
        "aliases": ["neighbor", "neighbour"],
        "description": "Neighbor as the human object loved out of charity in God.",
        "notes": [],
        "parent_concept_id": None,
        "registry_status": "seed",
        "disambiguation_notes": ["Do not collapse this into enemy-love or ecclesial unity without explicit passage support."],
        "related_concepts": ["concept.charity"],
        "introduced_in_questions": ["st.ii-ii.q025"],
    },
    {
        "concept_id": "concept.holy_spirit",
        "canonical_label": "Holy Spirit",
        "node_type": "doctrine",
        "aliases": ["holy spirit", "holy ghost"],
        "description": "The Holy Spirit in relation to infused charity and the named gifts.",
        "notes": [],
        "parent_concept_id": None,
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.charity", "concept.gift_holy_spirit"],
        "introduced_in_questions": ["st.ii-ii.q014", "st.ii-ii.q024"],
    },
    {
        "concept_id": "concept.joy",
        "canonical_label": "Joy",
        "node_type": "act_type",
        "aliases": ["joy", "spiritual joy"],
        "description": "Spiritual joy in God proceeding from charity.",
        "notes": [],
        "parent_concept_id": None,
        "registry_status": "seed",
        "disambiguation_notes": ["Keep distinct from merely sensible delight or pleasure."],
        "related_concepts": ["concept.charity", "concept.sloth"],
        "introduced_in_questions": ["st.ii-ii.q028", "st.ii-ii.q035"],
    },
    {
        "concept_id": "concept.peace",
        "canonical_label": "Peace",
        "node_type": "act_type",
        "aliases": ["peace", "peaceableness"],
        "description": "The ordered tranquility and union effected by charity.",
        "notes": [],
        "parent_concept_id": None,
        "registry_status": "seed",
        "disambiguation_notes": ["Keep distinct from mere political quiet or absence of conflict."],
        "related_concepts": ["concept.charity", "concept.discord", "concept.sedition"],
        "introduced_in_questions": ["st.ii-ii.q029"],
    },
    {
        "concept_id": "concept.mercy",
        "canonical_label": "Mercy",
        "node_type": "act_type",
        "aliases": ["mercy"],
        "description": "Merciful movement or act as treated in the charity tract.",
        "notes": [],
        "parent_concept_id": None,
        "registry_status": "seed",
        "disambiguation_notes": ["The tract can speak of mercy both as passion and as virtue-like act; keep evidence close to the cited passage."],
        "related_concepts": ["concept.charity", "concept.almsgiving"],
        "introduced_in_questions": ["st.ii-ii.q030", "st.ii-ii.q032"],
    },
    {
        "concept_id": "concept.beneficence",
        "canonical_label": "Beneficence",
        "node_type": "act_type",
        "aliases": ["beneficence"],
        "description": "Doing good to another as an act of friendship and charity.",
        "notes": [],
        "parent_concept_id": None,
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.charity"],
        "introduced_in_questions": ["st.ii-ii.q031"],
    },
    {
        "concept_id": "concept.almsgiving",
        "canonical_label": "Almsgiving",
        "node_type": "act_type",
        "aliases": ["almsgiving", "almsdeed", "almsdeeds"],
        "description": "Giving to the needy as an act of mercy and, through mercy, of charity.",
        "notes": [],
        "parent_concept_id": None,
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.mercy", "concept.charity"],
        "introduced_in_questions": ["st.ii-ii.q032"],
    },
    {
        "concept_id": "concept.fraternal_correction",
        "canonical_label": "Fraternal Correction",
        "node_type": "act_type",
        "aliases": ["fraternal correction"],
        "description": "Correction of a brother's sin as an act of charity ordered to amendment.",
        "notes": [],
        "parent_concept_id": None,
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.charity"],
        "introduced_in_questions": ["st.ii-ii.q033"],
    },
    {
        "concept_id": "concept.hatred_sin",
        "canonical_label": "Hatred (Sin)",
        "node_type": "sin_type",
        "aliases": ["hatred"],
        "description": "Sinful hatred opposed to the love due to God or neighbor.",
        "notes": [],
        "parent_concept_id": "concept.sin",
        "registry_status": "seed",
        "disambiguation_notes": ["Keep distinct from hatred as a passion treated in the Prima Secundae."],
        "related_concepts": ["concept.charity", "concept.love_act"],
        "introduced_in_questions": ["st.ii-ii.q034"],
    },
    {
        "concept_id": "concept.sloth",
        "canonical_label": "Sloth",
        "node_type": "sin_type",
        "aliases": ["sloth"],
        "description": "Oppressive sorrow about spiritual good, contrary to charity's joy.",
        "notes": [],
        "parent_concept_id": "concept.sin",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.charity", "concept.joy"],
        "introduced_in_questions": ["st.ii-ii.q035"],
    },
    {
        "concept_id": "concept.envy",
        "canonical_label": "Envy",
        "node_type": "sin_type",
        "aliases": ["envy"],
        "description": "Grief over a neighbor's good in a way contrary to charity.",
        "notes": [],
        "parent_concept_id": "concept.sin",
        "registry_status": "seed",
        "disambiguation_notes": ["Question 14 also names envy of a brother's spiritual good as a sin-against-the-Spirit species; do not collapse the broader and narrower uses silently."],
        "related_concepts": ["concept.charity", "concept.blasphemy_against_holy_spirit"],
        "introduced_in_questions": ["st.ii-ii.q014", "st.ii-ii.q036"],
    },
    {
        "concept_id": "concept.concord",
        "canonical_label": "Concord",
        "node_type": "act_type",
        "aliases": ["concord"],
        "description": "Agreement of hearts directed together by charity.",
        "notes": [],
        "parent_concept_id": None,
        "registry_status": "seed",
        "disambiguation_notes": ["Keep distinct from peace, though the tract closely relates them."],
        "related_concepts": ["concept.charity", "concept.discord", "concept.peace"],
        "introduced_in_questions": ["st.ii-ii.q037"],
    },
    {
        "concept_id": "concept.discord",
        "canonical_label": "Discord",
        "node_type": "sin_type",
        "aliases": ["discord"],
        "description": "Dissent of wills contrary to the concord produced by charity.",
        "notes": [],
        "parent_concept_id": "concept.sin",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.concord", "concept.charity"],
        "introduced_in_questions": ["st.ii-ii.q037"],
    },
    {
        "concept_id": "concept.contention",
        "canonical_label": "Contention",
        "node_type": "sin_type",
        "aliases": ["contention"],
        "description": "Contrariety of speech in a disordered or truth-disclaiming manner.",
        "notes": [],
        "parent_concept_id": "concept.sin",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.discord"],
        "introduced_in_questions": ["st.ii-ii.q038"],
    },
    {
        "concept_id": "concept.ecclesial_unity",
        "canonical_label": "Ecclesial Unity",
        "node_type": "doctrine",
        "aliases": ["unity of the church", "unity of spirit"],
        "description": "The unity of the Church and its members described as an effect of charity.",
        "notes": [],
        "parent_concept_id": None,
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.charity", "concept.schism"],
        "introduced_in_questions": ["st.ii-ii.q039"],
    },
    {
        "concept_id": "concept.schism",
        "canonical_label": "Schism",
        "node_type": "sin_type",
        "aliases": ["schism", "schismatic"],
        "description": "Scission from ecclesial unity, directly opposed to the unity effected by charity.",
        "notes": [],
        "parent_concept_id": "concept.sin",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.ecclesial_unity", "concept.charity"],
        "introduced_in_questions": ["st.ii-ii.q039"],
    },
    {
        "concept_id": "concept.war",
        "canonical_label": "War",
        "node_type": "sin_type",
        "aliases": ["war"],
        "description": "War as treated in the charity tract under the conditions of justice and peace.",
        "notes": [],
        "parent_concept_id": "concept.sin",
        "registry_status": "seed",
        "disambiguation_notes": ["The tract distinguishes just from unjust war; do not flatten every war reference into a sinful relation."],
        "related_concepts": ["concept.peace", "concept.common_good"],
        "introduced_in_questions": ["st.ii-ii.q040"],
    },
    {
        "concept_id": "concept.strife",
        "canonical_label": "Strife",
        "node_type": "sin_type",
        "aliases": ["strife"],
        "description": "Private war or contradiction of deeds between persons.",
        "notes": [],
        "parent_concept_id": "concept.war",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.war"],
        "introduced_in_questions": ["st.ii-ii.q041"],
    },
    {
        "concept_id": "concept.sedition",
        "canonical_label": "Sedition",
        "node_type": "sin_type",
        "aliases": ["sedition", "seditions"],
        "description": "Tumult or antagonism between parts of one people, opposed to civic unity and peace.",
        "notes": [],
        "parent_concept_id": "concept.sin",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.peace"],
        "introduced_in_questions": ["st.ii-ii.q042"],
    },
    {
        "concept_id": "concept.scandal",
        "canonical_label": "Scandal",
        "node_type": "sin_type",
        "aliases": ["scandal"],
        "description": "Something less rightly done or said that occasions another's spiritual downfall.",
        "notes": [],
        "parent_concept_id": "concept.sin",
        "registry_status": "seed",
        "disambiguation_notes": ["Keep active and passive scandal distinct at the annotation level when the passage requires it."],
        "related_concepts": ["concept.charity"],
        "introduced_in_questions": ["st.ii-ii.q043"],
    },
    {
        "concept_id": "concept.precepts_of_charity",
        "canonical_label": "Precepts of Charity",
        "node_type": "precept",
        "aliases": ["precepts of charity"],
        "description": "Precepts whose end and ordering belong to charity.",
        "notes": [],
        "parent_concept_id": "concept.precept",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.charity"],
        "introduced_in_questions": ["st.ii-ii.q044"],
    },
    {
        "concept_id": "concept.folly",
        "canonical_label": "Folly",
        "node_type": "sin_type",
        "aliases": ["folly"],
        "description": "Dulled judgment in divine things, treated as contrary to wisdom.",
        "notes": [],
        "parent_concept_id": "concept.sin",
        "registry_status": "seed",
        "disambiguation_notes": [],
        "related_concepts": ["concept.wisdom_gift"],
        "introduced_in_questions": ["st.ii-ii.q046"],
    },
]

SUPPRESSED_SINGLE_TOKEN_LABELS = {
    "act",
    "contention",
    "despair",
    "end",
    "envy",
    "folly",
    "grace",
    "habit",
    "hatred",
    "joy",
    "law",
    "mercy",
    "neighbor",
    "peace",
    "reason",
    "scandal",
    "sin",
    "sloth",
    "strife",
    "use",
    "vice",
    "virtue",
    "will",
    "war",
}

DETECTION_LABEL_OVERRIDES = {
    "concept.faith": ["faith"],
    "concept.hope": ["hope"],
    "concept.charity": ["charity"],
    "concept.prudence": ["prudence"],
    "concept.justice": ["justice"],
    "concept.fortitude": ["fortitude"],
    "concept.temperance": ["temperance"],
    "concept.anger": ["anger"],
    "concept.fear": ["fear"],
    "concept.desire": ["desire"],
    "concept.hatred": ["hatred"],
    "concept.love_passion": ["love"],
    "concept.natural_law": ["natural law"],
    "concept.eternal_law": ["eternal law"],
    "concept.human_law": ["human law"],
    "concept.divine_law": ["divine law"],
    "concept.operating_grace": ["operating grace"],
    "concept.cooperating_grace": ["cooperating grace"],
    "concept.ultimate_end": ["ultimate end", "last end"],
    "concept.symbol_of_faith": ["symbol of faith", "creed"],
}

RELATION_CUE_PATTERNS: list[tuple[str, PilotRelationType, str]] = [
    ("cue_contrary", "contrary_to", r"\bcontrary to\b"),
    ("cue_opposed", "opposed_by", r"\bopposed to\b"),
    ("cue_corresponds", "corresponds_to", r"\bcorresponds to\b"),
    ("cue_species", "species_of", r"\bspecies of\b"),
    ("cue_part", "part_of", r"\bpart of\b"),
    ("cue_regulated", "regulated_by", r"\bregulated by\b"),
    ("cue_perfected", "perfected_by", r"\bperfected by\b"),
    ("cue_directed", "directed_to", r"\bdirected to\b"),
]
