from __future__ import annotations

from dataclasses import dataclass

from ..models.prudence import (
    PrudenceConceptRecord,
    PrudenceRelationType,
    SupportType,
)


def resp_id(question_number: int, article_number: int) -> str:
    return f"st.ii-ii.q{question_number:03d}.a{article_number:03d}.resp"


def article_id(question_number: int, article_number: int) -> str:
    return f"st.ii-ii.q{question_number:03d}.a{article_number:03d}"


def question_id(question_number: int) -> str:
    return f"st.ii-ii.q{question_number:03d}"


@dataclass(frozen=True)
class RelationSeed:
    source_passage_id: str
    subject_id: str
    relation_type: PrudenceRelationType
    object_id: str
    support_type: SupportType
    confidence: float
    rationale: str
    evidence_hints: tuple[str, ...]


REVIEWED_CONCEPTS = [
    {
        "concept_id": "concept.prudence",
        "label": "Prudence",
        "node_type": "virtue",
        "aliases": ["prudence"],
        "description": "The cardinal virtue of right practical reason in things to be done.",
        "disambiguation_note": None,
        "review_status": "approved",
        "part_taxonomy": None,
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.reason_faculty",
        "label": "Reason",
        "node_type": "faculty",
        "aliases": ["reason"],
        "description": "The rational cognitive faculty in which prudence is located.",
        "disambiguation_note": "Keep distinct from Reasoning, the integral part of prudence in Q49 a5.",
        "review_status": "approved",
        "part_taxonomy": None,
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.practical_reason",
        "label": "Practical Reason",
        "node_type": "faculty",
        "aliases": ["practical reason"],
        "description": "Reason as ordered to action and counsel.",
        "disambiguation_note": "Do not collapse into reason_faculty when the tract is specifically distinguishing practical from speculative reason.",
        "review_status": "approved",
        "part_taxonomy": None,
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.command",
        "label": "Command",
        "node_type": "act",
        "aliases": ["command"],
        "description": "The principal act of prudence in commanding action.",
        "disambiguation_note": None,
        "review_status": "approved",
        "part_taxonomy": None,
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.solicitude",
        "label": "Solicitude",
        "node_type": "act",
        "aliases": ["solicitude", "watchfulness"],
        "description": "Prompt practical watchfulness treated as belonging to prudence.",
        "disambiguation_note": "Keep separate from unlawful solicitude about temporal or future things in Q55.",
        "review_status": "approved",
        "part_taxonomy": None,
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.common_good",
        "label": "Common Good",
        "node_type": "end",
        "aliases": ["common good"],
        "description": "The communal end to which public prudence is ordered.",
        "disambiguation_note": None,
        "review_status": "approved",
        "part_taxonomy": None,
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.false_prudence",
        "label": "False Prudence",
        "node_type": "vice",
        "aliases": ["false prudence"],
        "description": "A prudence-like likeness directed to an apparent good rather than true good.",
        "disambiguation_note": "Keep distinct from craftiness and prudence of the flesh.",
        "review_status": "approved",
        "part_taxonomy": None,
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.memory",
        "label": "Memory",
        "node_type": "prudence_part",
        "aliases": ["memory"],
        "description": "Integral part of prudence concerning past experience.",
        "disambiguation_note": None,
        "review_status": "approved",
        "part_taxonomy": "integral",
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.intelligence",
        "label": "Understanding or Intelligence",
        "node_type": "prudence_part",
        "aliases": ["understanding", "intelligence"],
        "description": "Integral part of prudence concerning right estimate of first practical principles.",
        "disambiguation_note": "Do not collapse into the distinct gift of understanding from elsewhere in the corpus.",
        "review_status": "approved",
        "part_taxonomy": "integral",
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.docility",
        "label": "Docility",
        "node_type": "prudence_part",
        "aliases": ["docility"],
        "description": "Integral part of prudence disposing a person to learn from others.",
        "disambiguation_note": None,
        "review_status": "approved",
        "part_taxonomy": "integral",
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.shrewdness",
        "label": "Shrewdness",
        "node_type": "prudence_part",
        "aliases": ["shrewdness", "eustochia"],
        "description": "Integral part of prudence signifying apt discovery of the fitting course.",
        "disambiguation_note": "The source sometimes glosses this through eustochia; keep the prudence-part label stable.",
        "review_status": "approved",
        "part_taxonomy": "integral",
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.reasoning",
        "label": "Reasoning",
        "node_type": "prudence_part",
        "aliases": ["reasoning", "reason"],
        "description": "Integral part of prudence in comparing one thing with another during counsel.",
        "disambiguation_note": "Distinguish from reason_faculty, the cognitive power in which prudence resides.",
        "review_status": "approved",
        "part_taxonomy": "integral",
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.foresight",
        "label": "Foresight",
        "node_type": "prudence_part",
        "aliases": ["foresight"],
        "description": "Integral part of prudence ordering means fittingly to the end.",
        "disambiguation_note": None,
        "review_status": "approved",
        "part_taxonomy": "integral",
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.circumspection",
        "label": "Circumspection",
        "node_type": "prudence_part",
        "aliases": ["circumspection"],
        "description": "Integral part of prudence attending to relevant circumstances.",
        "disambiguation_note": None,
        "review_status": "approved",
        "part_taxonomy": "integral",
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.caution",
        "label": "Caution",
        "node_type": "prudence_part",
        "aliases": ["caution"],
        "description": "Integral part of prudence avoiding evils mixed with apparent goods.",
        "disambiguation_note": None,
        "review_status": "approved",
        "part_taxonomy": "integral",
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.regnative_prudence",
        "label": "Regnative Prudence",
        "node_type": "prudence_part",
        "aliases": ["regnative prudence", "regnative"],
        "description": "Subjective part of prudence belonging to rulers of a city or kingdom.",
        "disambiguation_note": None,
        "review_status": "approved",
        "part_taxonomy": "subjective",
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.political_prudence",
        "label": "Political Prudence",
        "node_type": "prudence_part",
        "aliases": ["political prudence", "political"],
        "description": "Subjective part of prudence in subjects directing themselves in obedience.",
        "disambiguation_note": "Article 50.2 uses the title 'political economy' in this edition; normalize the concept label as Political Prudence.",
        "review_status": "approved",
        "part_taxonomy": "subjective",
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.domestic_prudence",
        "label": "Domestic Prudence",
        "node_type": "prudence_part",
        "aliases": ["domestic prudence", "domestic economy"],
        "description": "Subjective part of prudence governing the household.",
        "disambiguation_note": "The source title uses 'domestic economy'; the normalized concept remains Domestic Prudence.",
        "review_status": "approved",
        "part_taxonomy": "subjective",
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.military_prudence",
        "label": "Military Prudence",
        "node_type": "prudence_part",
        "aliases": ["military prudence", "military"],
        "description": "Subjective part of prudence repelling hostile attacks for the common good.",
        "disambiguation_note": None,
        "review_status": "approved",
        "part_taxonomy": "subjective",
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.euboulia",
        "label": "Euboulia",
        "node_type": "prudence_part",
        "aliases": ["euboulia", "deliberating well", "good counsel"],
        "description": "Potential part of prudence concerned with good counsel.",
        "disambiguation_note": "Keep the transliterated term because the tract names it directly.",
        "review_status": "approved",
        "part_taxonomy": "potential",
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.synesis",
        "label": "Synesis",
        "node_type": "prudence_part",
        "aliases": ["synesis", "judging well according to common law"],
        "description": "Potential part of prudence concerned with good judgment under common law.",
        "disambiguation_note": "Keep separate from gnome.",
        "review_status": "approved",
        "part_taxonomy": "potential",
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.gnome",
        "label": "Gnome",
        "node_type": "prudence_part",
        "aliases": ["gnome", "judging according to general law"],
        "description": "Potential part of prudence judging according to higher principles in exceptional cases.",
        "disambiguation_note": "Keep separate from synesis and from prudence generally.",
        "review_status": "approved",
        "part_taxonomy": "potential",
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.counsel_gift",
        "label": "Gift of Counsel",
        "node_type": "gift_holy_spirit",
        "aliases": ["gift of counsel", "counsel"],
        "description": "The corresponding gift of the Holy Ghost perfecting prudence.",
        "disambiguation_note": "Keep distinct from counsel as an act of deliberation.",
        "review_status": "approved",
        "part_taxonomy": None,
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.mercy_beatitude",
        "label": "Beatitude of Mercy",
        "node_type": "beatitude",
        "aliases": ["merciful", "mercy"],
        "description": "The fifth beatitude associated here with the gift of counsel.",
        "disambiguation_note": None,
        "review_status": "approved",
        "part_taxonomy": None,
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.imprudence",
        "label": "Imprudence",
        "node_type": "vice",
        "aliases": ["imprudence"],
        "description": "Vice opposed to prudence through lack or contrary movement of reason.",
        "disambiguation_note": None,
        "review_status": "approved",
        "part_taxonomy": None,
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.precipitation",
        "label": "Precipitation or Temerity",
        "node_type": "defect",
        "aliases": ["precipitation", "temerity"],
        "description": "Defect of counsel contained under imprudence.",
        "disambiguation_note": None,
        "review_status": "approved",
        "part_taxonomy": None,
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.thoughtlessness",
        "label": "Thoughtlessness",
        "node_type": "defect",
        "aliases": ["thoughtlessness"],
        "description": "Defect of right judgment treated under imprudence.",
        "disambiguation_note": None,
        "review_status": "approved",
        "part_taxonomy": None,
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.inconstancy",
        "label": "Inconstancy",
        "node_type": "defect",
        "aliases": ["inconstancy"],
        "description": "Defect of command withdrawing from a good purpose.",
        "disambiguation_note": None,
        "review_status": "approved",
        "part_taxonomy": None,
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.negligence",
        "label": "Negligence",
        "node_type": "defect",
        "aliases": ["negligence"],
        "description": "Lack of due solicitude treated as pertaining to imprudence.",
        "disambiguation_note": None,
        "review_status": "approved",
        "part_taxonomy": None,
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.prudence_of_flesh",
        "label": "Prudence of the Flesh",
        "node_type": "vice",
        "aliases": ["prudence of the flesh", "carnal prudence"],
        "description": "Counterfeit prudence that treats bodily goods as the last end of life.",
        "disambiguation_note": "Keep distinct from false prudence and from craftiness.",
        "review_status": "approved",
        "part_taxonomy": None,
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.craftiness",
        "label": "Craftiness",
        "node_type": "vice",
        "aliases": ["craftiness"],
        "description": "Counterfeit prudence using fictitious or counterfeit means.",
        "disambiguation_note": None,
        "review_status": "approved",
        "part_taxonomy": None,
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.guile",
        "label": "Guile",
        "node_type": "vice",
        "aliases": ["guile"],
        "description": "Execution of craftiness in words or deeds.",
        "disambiguation_note": "Keep distinct from fraud, which is more properly by deeds.",
        "review_status": "approved",
        "part_taxonomy": None,
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.fraud",
        "label": "Fraud",
        "node_type": "vice",
        "aliases": ["fraud"],
        "description": "Execution of craftiness more properly by deeds.",
        "disambiguation_note": None,
        "review_status": "approved",
        "part_taxonomy": None,
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.temporal_solicitude",
        "label": "Solicitude about Temporal Things",
        "node_type": "defect",
        "aliases": ["solicitude about temporal things", "temporal things", "care of this world"],
        "description": "Unlawful solicitude seeking temporal things as end or with undue anxiety.",
        "disambiguation_note": "Keep distinct from solicitude as a prudential act in Q47 a9.",
        "review_status": "approved",
        "part_taxonomy": None,
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.future_solicitude",
        "label": "Solicitude about the Future",
        "node_type": "defect",
        "aliases": ["solicitude about the future", "solicitous for tomorrow", "for tomorrow"],
        "description": "Needlessly forestalling solicitude proper to a future time.",
        "disambiguation_note": "Keep distinct from lawful prudential foresight.",
        "review_status": "approved",
        "part_taxonomy": None,
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.covetousness",
        "label": "Covetousness",
        "node_type": "vice",
        "aliases": ["covetousness"],
        "description": "Vice named as the chief origin of counterfeit prudence-like forms in Q55 a8.",
        "disambiguation_note": None,
        "review_status": "approved",
        "part_taxonomy": None,
        "unresolved_note": None,
    },
    {
        "concept_id": "concept.lust",
        "label": "Lust",
        "node_type": "vice",
        "aliases": ["lust"],
        "description": "Vice named as chief origin of defects of prudence in Q53 a6.",
        "disambiguation_note": None,
        "review_status": "approved",
        "part_taxonomy": None,
        "unresolved_note": None,
    },
    {
        "concept_id": "taxonomy.prudence_core",
        "label": "Prudence Core Tract",
        "node_type": "taxonomy",
        "aliases": ["prudence core"],
        "description": "Editorial tract marker for prudence itself in QQ. 47–48.",
        "disambiguation_note": None,
        "review_status": "approved",
        "part_taxonomy": None,
        "unresolved_note": None,
    },
    {
        "concept_id": "taxonomy.integral_parts_prudence",
        "label": "Integral Parts of Prudence",
        "node_type": "taxonomy",
        "aliases": ["integral parts of prudence"],
        "description": "Editorial grouping node for prudence's integral parts.",
        "disambiguation_note": None,
        "review_status": "approved",
        "part_taxonomy": None,
        "unresolved_note": None,
    },
    {
        "concept_id": "taxonomy.subjective_parts_prudence",
        "label": "Subjective Parts of Prudence",
        "node_type": "taxonomy",
        "aliases": ["subjective parts of prudence"],
        "description": "Editorial grouping node for prudence's subjective parts.",
        "disambiguation_note": None,
        "review_status": "approved",
        "part_taxonomy": None,
        "unresolved_note": None,
    },
    {
        "concept_id": "taxonomy.potential_parts_prudence",
        "label": "Potential Parts of Prudence",
        "node_type": "taxonomy",
        "aliases": ["potential parts of prudence"],
        "description": "Editorial grouping node for prudence's potential parts.",
        "disambiguation_note": None,
        "review_status": "approved",
        "part_taxonomy": None,
        "unresolved_note": None,
    },
    {
        "concept_id": "taxonomy.gift_of_counsel",
        "label": "Gift of Counsel Tract",
        "node_type": "taxonomy",
        "aliases": ["gift of counsel"],
        "description": "Editorial grouping node for the gift of counsel material.",
        "disambiguation_note": None,
        "review_status": "approved",
        "part_taxonomy": None,
        "unresolved_note": None,
    },
    {
        "concept_id": "taxonomy.prudence_defects",
        "label": "Defects Opposed to Prudence",
        "node_type": "taxonomy",
        "aliases": ["prudence defects"],
        "description": "Editorial grouping node for imprudence and allied defects.",
        "disambiguation_note": None,
        "review_status": "approved",
        "part_taxonomy": None,
        "unresolved_note": None,
    },
    {
        "concept_id": "taxonomy.counterfeit_prudence",
        "label": "Counterfeit Prudence Forms",
        "node_type": "taxonomy",
        "aliases": ["counterfeit prudence"],
        "description": "Editorial grouping node for prudence-like but misdirected forms.",
        "disambiguation_note": None,
        "review_status": "approved",
        "part_taxonomy": None,
        "unresolved_note": None,
    },
    {
        "concept_id": "taxonomy.prudence_precepts",
        "label": "Precepts of Prudence",
        "node_type": "taxonomy",
        "aliases": ["precepts of prudence"],
        "description": "Editorial grouping node for the precept material in Q56.",
        "disambiguation_note": None,
        "review_status": "approved",
        "part_taxonomy": None,
        "unresolved_note": None,
    },
]


CONCEPT_SEARCH_TERMS = {
    record.concept_id: tuple(record.aliases)
    for record in (PrudenceConceptRecord.model_validate(concept) for concept in REVIEWED_CONCEPTS)
}


ARTICLE_TREATED_IN_MAP: list[tuple[str, str, SupportType, float]] = []


def add_treated_in(
    passage: str,
    concept_id: str,
    support_type: SupportType = "explicit_textual",
    confidence: float = 0.94,
) -> None:
    ARTICLE_TREATED_IN_MAP.append((passage, concept_id, support_type, confidence))


for article_number in range(1, 17):
    add_treated_in(resp_id(47, article_number), "concept.prudence")
for article_number, concept_id in {
    1: "concept.reason_faculty",
    2: "concept.practical_reason",
    8: "concept.command",
    9: "concept.solicitude",
    10: "concept.common_good",
    11: "concept.common_good",
    13: "concept.false_prudence",
}.items():
    add_treated_in(resp_id(47, article_number), concept_id)

add_treated_in(resp_id(48, 1), "concept.prudence")
for concept_id in (
    "concept.memory",
    "concept.intelligence",
    "concept.docility",
    "concept.shrewdness",
    "concept.reasoning",
    "concept.foresight",
    "concept.circumspection",
    "concept.caution",
    "concept.regnative_prudence",
    "concept.political_prudence",
    "concept.domestic_prudence",
    "concept.military_prudence",
    "concept.euboulia",
    "concept.synesis",
    "concept.gnome",
):
    add_treated_in(resp_id(48, 1), concept_id)

for article_number, concept_id in {
    1: "concept.memory",
    2: "concept.intelligence",
    3: "concept.docility",
    4: "concept.shrewdness",
    5: "concept.reasoning",
    6: "concept.foresight",
    7: "concept.circumspection",
    8: "concept.caution",
}.items():
    add_treated_in(resp_id(49, article_number), "concept.prudence")
    add_treated_in(resp_id(49, article_number), concept_id)

for article_number, concept_id in {
    1: "concept.regnative_prudence",
    2: "concept.political_prudence",
    3: "concept.domestic_prudence",
    4: "concept.military_prudence",
}.items():
    add_treated_in(resp_id(50, article_number), "concept.prudence")
    add_treated_in(resp_id(50, article_number), concept_id)

for article_number, concept_id in {
    1: "concept.euboulia",
    2: "concept.euboulia",
    3: "concept.synesis",
    4: "concept.gnome",
}.items():
    prudence_support: SupportType = (
        "strong_textual_inference" if article_number in {1, 4} else "explicit_textual"
    )
    add_treated_in(
        resp_id(51, article_number),
        "concept.prudence",
        support_type=prudence_support,
        confidence=0.91,
    )
    add_treated_in(resp_id(51, article_number), concept_id)

for article_number in range(1, 5):
    add_treated_in(resp_id(52, article_number), "concept.counsel_gift")
add_treated_in(resp_id(52, 2), "concept.prudence")
add_treated_in(resp_id(52, 4), "concept.mercy_beatitude")

for article_number in range(1, 7):
    support_type: SupportType = (
        "strong_textual_inference" if article_number in {4, 6} else "explicit_textual"
    )
    add_treated_in(
        resp_id(53, article_number), "concept.imprudence", support_type=support_type, confidence=0.9
    )
for article_number, concept_id in {
    3: "concept.precipitation",
    4: "concept.thoughtlessness",
    5: "concept.inconstancy",
    6: "concept.lust",
}.items():
    add_treated_in(resp_id(53, article_number), concept_id)

for article_number in range(1, 4):
    add_treated_in(resp_id(54, article_number), "concept.negligence")
add_treated_in(resp_id(54, 2), "concept.prudence")
add_treated_in(resp_id(54, 2), "concept.solicitude")

for article_number, concept_id in {
    1: "concept.prudence_of_flesh",
    2: "concept.prudence_of_flesh",
    3: "concept.craftiness",
    4: "concept.guile",
    5: "concept.fraud",
    6: "concept.temporal_solicitude",
    7: "concept.future_solicitude",
}.items():
    add_treated_in(resp_id(55, article_number), concept_id)
add_treated_in(resp_id(55, 1), "concept.prudence", confidence=0.9)
add_treated_in(resp_id(55, 3), "concept.prudence", confidence=0.9)
for concept_id in (
    "concept.craftiness",
    "concept.guile",
    "concept.fraud",
    "concept.prudence_of_flesh",
    "concept.covetousness",
):
    add_treated_in(resp_id(55, 8), concept_id)

add_treated_in(resp_id(56, 1), "concept.prudence")
add_treated_in(
    resp_id(56, 2), "concept.prudence", support_type="strong_textual_inference", confidence=0.84
)
add_treated_in(resp_id(56, 2), "concept.craftiness", confidence=0.88)


RELATION_SEEDS = [
    RelationSeed(
        resp_id(47, 1),
        "concept.prudence",
        "resides_in",
        "concept.reason_faculty",
        "strong_textual_inference",
        0.9,
        "The respondeo places prudence in the cognitive power rather than the appetitive power, which in this article is the rational faculty of reason.",
        ("prudence belongs directly to the cognitive", "obtain knowledge of the future"),
    ),
    RelationSeed(
        resp_id(47, 2),
        "concept.prudence",
        "resides_in",
        "concept.practical_reason",
        "explicit_textual",
        0.98,
        "The passage explicitly states that prudence resides only in the practical reason.",
        ("prudence resides only in the practical reason", "practical reason"),
    ),
    RelationSeed(
        resp_id(47, 8),
        "concept.prudence",
        "has_act",
        "concept.command",
        "explicit_textual",
        0.97,
        "The passage identifies command as the chief act of prudence.",
        ("the chief act of prudence", "command"),
    ),
    RelationSeed(
        resp_id(47, 9),
        "concept.prudence",
        "has_act",
        "concept.solicitude",
        "explicit_textual",
        0.96,
        "The passage explicitly says solicitude belongs to prudence.",
        ("this belongs to prudence", "solicitude"),
    ),
    RelationSeed(
        resp_id(47, 10),
        "concept.prudence",
        "directed_to",
        "concept.common_good",
        "explicit_textual",
        0.95,
        "The respondeo extends prudence to the common good rather than private good only.",
        ("common good", "prudence does not extend to the common good"),
    ),
    RelationSeed(
        resp_id(48, 1),
        "concept.memory",
        "integral_part_of",
        "concept.prudence",
        "explicit_textual",
        0.99,
        "Q48 explicitly enumerates memory among the integral parts of prudence.",
        ("memory", "parts of prudence"),
    ),
    RelationSeed(
        resp_id(48, 1),
        "concept.intelligence",
        "integral_part_of",
        "concept.prudence",
        "explicit_textual",
        0.99,
        "Q48 explicitly enumerates understanding or intelligence among the integral parts of prudence.",
        ("understanding", "parts of prudence"),
    ),
    RelationSeed(
        resp_id(48, 1),
        "concept.docility",
        "integral_part_of",
        "concept.prudence",
        "explicit_textual",
        0.99,
        "Q48 explicitly enumerates docility among the integral parts of prudence.",
        ("docility", "parts of prudence"),
    ),
    RelationSeed(
        resp_id(48, 1),
        "concept.shrewdness",
        "integral_part_of",
        "concept.prudence",
        "explicit_textual",
        0.99,
        "Q48 explicitly enumerates shrewdness among the integral parts of prudence.",
        ("shrewdness", "parts of prudence"),
    ),
    RelationSeed(
        resp_id(48, 1),
        "concept.reasoning",
        "integral_part_of",
        "concept.prudence",
        "explicit_textual",
        0.99,
        "Q48 explicitly enumerates reasoning among the integral parts of prudence.",
        ("reasoning", "parts of prudence"),
    ),
    RelationSeed(
        resp_id(48, 1),
        "concept.foresight",
        "integral_part_of",
        "concept.prudence",
        "explicit_textual",
        0.99,
        "Q48 explicitly enumerates foresight among the integral parts of prudence.",
        ("foresight", "parts of prudence"),
    ),
    RelationSeed(
        resp_id(48, 1),
        "concept.circumspection",
        "integral_part_of",
        "concept.prudence",
        "explicit_textual",
        0.99,
        "Q48 explicitly enumerates circumspection among the integral parts of prudence.",
        ("circumspection", "parts of prudence"),
    ),
    RelationSeed(
        resp_id(48, 1),
        "concept.caution",
        "integral_part_of",
        "concept.prudence",
        "explicit_textual",
        0.99,
        "Q48 explicitly enumerates caution among the integral parts of prudence.",
        ("caution", "parts of prudence"),
    ),
    RelationSeed(
        resp_id(48, 1),
        "concept.regnative_prudence",
        "subjective_part_of",
        "concept.prudence",
        "explicit_textual",
        0.99,
        "Q48 explicitly enumerates regnative prudence among the subjective parts.",
        ("regnative prudence", "The subjective parts"),
    ),
    RelationSeed(
        resp_id(48, 1),
        "concept.political_prudence",
        "subjective_part_of",
        "concept.prudence",
        "explicit_textual",
        0.99,
        "Q48 explicitly enumerates political prudence among the subjective parts.",
        ("political prudence", "The subjective parts"),
    ),
    RelationSeed(
        resp_id(48, 1),
        "concept.domestic_prudence",
        "subjective_part_of",
        "concept.prudence",
        "explicit_textual",
        0.99,
        "Q48 explicitly enumerates domestic prudence among the subjective parts.",
        ("domestic prudence", "The subjective parts"),
    ),
    RelationSeed(
        resp_id(48, 1),
        "concept.military_prudence",
        "subjective_part_of",
        "concept.prudence",
        "explicit_textual",
        0.99,
        "Q48 explicitly enumerates military prudence among the subjective parts.",
        ("military", "The subjective parts"),
    ),
    RelationSeed(
        resp_id(48, 1),
        "concept.euboulia",
        "potential_part_of",
        "concept.prudence",
        "explicit_textual",
        0.99,
        "Q48 explicitly places good counsel among the potential parts of prudence.",
        ("good counsel", "The potential parts"),
    ),
    RelationSeed(
        resp_id(48, 1),
        "concept.synesis",
        "potential_part_of",
        "concept.prudence",
        "explicit_textual",
        0.99,
        "Q48 explicitly places synesis among the potential parts of prudence.",
        ("synesis", "The potential parts"),
    ),
    RelationSeed(
        resp_id(48, 1),
        "concept.gnome",
        "potential_part_of",
        "concept.prudence",
        "explicit_textual",
        0.99,
        "Q48 explicitly places gnome among the potential parts of prudence.",
        ("gnome", "The potential parts"),
    ),
    RelationSeed(
        resp_id(50, 1),
        "concept.regnative_prudence",
        "subjective_part_of",
        "concept.prudence",
        "explicit_textual",
        0.97,
        "Q50.1 explicitly reckons regnative as a species of prudence.",
        ("a species of prudence is reckoned to be regnative", "regnative"),
    ),
    RelationSeed(
        resp_id(50, 2),
        "concept.political_prudence",
        "subjective_part_of",
        "concept.prudence",
        "explicit_textual",
        0.96,
        "Q50.2 explicitly names political prudence as a species of prudence in subjects.",
        ("species of prudence which is called political", "political"),
    ),
    RelationSeed(
        resp_id(50, 3),
        "concept.domestic_prudence",
        "subjective_part_of",
        "concept.prudence",
        "explicit_textual",
        0.96,
        "Q50.3 explicitly distinguishes domestic prudence from political prudence and prudence of the individual.",
        ("domestic prudence", "must domestic prudence be distinct"),
    ),
    RelationSeed(
        resp_id(50, 4),
        "concept.military_prudence",
        "subjective_part_of",
        "concept.prudence",
        "explicit_textual",
        0.96,
        "Q50.4 explicitly says there should be military prudence alongside political prudence.",
        ("military prudence", "there should be not only"),
    ),
    RelationSeed(
        resp_id(52, 2),
        "concept.counsel_gift",
        "corresponds_to",
        "concept.prudence",
        "explicit_textual",
        0.99,
        "The passage explicitly says the gift of counsel corresponds to prudence.",
        ("the gift of counsel corresponds to prudence", "corresponds to prudence"),
    ),
    RelationSeed(
        resp_id(52, 2),
        "concept.prudence",
        "perfected_by",
        "concept.counsel_gift",
        "explicit_textual",
        0.98,
        "The passage explicitly says prudence is perfected and helped by the gift of counsel.",
        ("prudence", "perfected and helped"),
    ),
    RelationSeed(
        resp_id(52, 4),
        "concept.counsel_gift",
        "corresponds_to",
        "concept.mercy_beatitude",
        "explicit_textual",
        0.97,
        "The passage explicitly links the gift of counsel with the beatitude of mercy.",
        ("beatitude of mercy specially corresponds", "corresponds to the gift of counsel"),
    ),
    RelationSeed(
        resp_id(53, 1),
        "concept.imprudence",
        "opposed_by",
        "concept.prudence",
        "strong_textual_inference",
        0.92,
        "Imprudence is treated throughout Q53 as the vice lacking the rectitude of prudence.",
        ("imprudence denotes lack of that prudence", "movement or act of reason"),
    ),
    RelationSeed(
        resp_id(53, 3),
        "concept.precipitation",
        "species_of",
        "concept.imprudence",
        "explicit_textual",
        0.97,
        "The passage explicitly says precipitation is contained under imprudence.",
        ("the vice of precipitation is contained under imprudence", "contained under imprudence"),
    ),
    RelationSeed(
        resp_id(53, 4),
        "concept.thoughtlessness",
        "opposed_by",
        "concept.prudence",
        "strong_textual_inference",
        0.89,
        "Thoughtlessness is treated as lack of right judgment within the prudential tract.",
        ("thoughtlessness is a sin", "lack of right judgment"),
    ),
    RelationSeed(
        resp_id(53, 5),
        "concept.inconstancy",
        "species_of",
        "concept.imprudence",
        "explicit_textual",
        0.97,
        "The passage explicitly says inconstancy belongs to imprudence.",
        ("belongs to imprudence", "inconstancy"),
    ),
    RelationSeed(
        resp_id(53, 5),
        "concept.inconstancy",
        "contrary_to",
        "concept.command",
        "explicit_textual",
        0.95,
        "The passage explicitly says inconstancy arises from a defect in the act of command.",
        ("defect in the act of command", "inconstancy"),
    ),
    RelationSeed(
        resp_id(53, 6),
        "concept.precipitation",
        "caused_by",
        "concept.lust",
        "explicit_textual",
        0.93,
        "The passage says the aforesaid vices arise chiefly from lust.",
        ("arise chiefly from lust", "aforesaid vices"),
    ),
    RelationSeed(
        resp_id(53, 6),
        "concept.thoughtlessness",
        "caused_by",
        "concept.lust",
        "explicit_textual",
        0.93,
        "The passage says the aforesaid vices arise chiefly from lust.",
        ("arise chiefly from lust", "aforesaid vices"),
    ),
    RelationSeed(
        resp_id(53, 6),
        "concept.inconstancy",
        "caused_by",
        "concept.lust",
        "explicit_textual",
        0.93,
        "The passage says the aforesaid vices arise chiefly from lust.",
        ("arise chiefly from lust", "aforesaid vices"),
    ),
    RelationSeed(
        resp_id(54, 2),
        "concept.negligence",
        "species_of",
        "concept.imprudence",
        "explicit_textual",
        0.98,
        "The passage explicitly says negligence pertains to imprudence.",
        ("negligence pertains to imprudence", "pertains to imprudence"),
    ),
    RelationSeed(
        resp_id(54, 2),
        "concept.negligence",
        "contrary_to",
        "concept.solicitude",
        "explicit_textual",
        0.98,
        "The passage explicitly says negligence is directly opposed to solicitude.",
        ("Negligence is directly opposed to solicitude", "directly opposed to solicitude"),
    ),
    RelationSeed(
        resp_id(55, 1),
        "concept.prudence_of_flesh",
        "opposed_by",
        "concept.prudence",
        "strong_textual_inference",
        0.92,
        "Prudence of the flesh is presented as a sinful counterfeit of prudence ordered to the wrong end.",
        (
            "prudence of the flesh signifies",
            "prudence regards things which are directed to the end",
        ),
    ),
    RelationSeed(
        resp_id(55, 3),
        "concept.craftiness",
        "opposed_by",
        "concept.prudence",
        "explicit_textual",
        0.96,
        "The passage explicitly says craftiness is a sin opposed to prudence.",
        ("a sin opposed to prudence", "craftiness"),
    ),
    RelationSeed(
        resp_id(55, 4),
        "concept.guile",
        "caused_by",
        "concept.craftiness",
        "strong_textual_inference",
        0.9,
        "Guile is defined as the execution of craftiness.",
        ("guile denotes a certain execution of craftiness", "belongs thereto"),
    ),
    RelationSeed(
        resp_id(55, 5),
        "concept.fraud",
        "caused_by",
        "concept.craftiness",
        "strong_textual_inference",
        0.88,
        "Fraud is defined as execution of craftiness by deeds.",
        ("fraud", "execution of craftiness"),
    ),
    RelationSeed(
        resp_id(55, 6),
        "concept.temporal_solicitude",
        "contrary_to",
        "concept.prudence",
        "strong_textual_inference",
        0.85,
        "Unlawful solicitude about temporal things is treated as disordered concern contrary to rightly ordered prudential search.",
        ("solicitude about temporal things may be unlawful", "drawn away from spiritual things"),
    ),
    RelationSeed(
        resp_id(55, 7),
        "concept.future_solicitude",
        "contrary_to",
        "concept.prudence",
        "strong_textual_inference",
        0.84,
        "Needlessly forestalling future solicitude is treated as lack of due order in practical concern.",
        ("Be . . . not solicitous for tomorrow", "needlessly forestalling"),
    ),
    RelationSeed(
        resp_id(55, 8),
        "concept.prudence_of_flesh",
        "caused_by",
        "concept.covetousness",
        "explicit_textual",
        0.94,
        "The passage explicitly says the aforesaid vices arise chiefly from covetousness.",
        ("arise chiefly from covetousness", "carnal prudence"),
    ),
    RelationSeed(
        resp_id(55, 8),
        "concept.craftiness",
        "caused_by",
        "concept.covetousness",
        "explicit_textual",
        0.94,
        "The passage explicitly says the aforesaid vices arise chiefly from covetousness.",
        ("arise chiefly from covetousness", "craftiness"),
    ),
    RelationSeed(
        resp_id(55, 8),
        "concept.guile",
        "caused_by",
        "concept.covetousness",
        "explicit_textual",
        0.94,
        "The passage explicitly says the aforesaid vices arise chiefly from covetousness.",
        ("arise chiefly from covetousness", "guile"),
    ),
    RelationSeed(
        resp_id(55, 8),
        "concept.fraud",
        "caused_by",
        "concept.covetousness",
        "explicit_textual",
        0.94,
        "The passage explicitly says the aforesaid vices arise chiefly from covetousness.",
        ("arise chiefly from covetousness", "fraud"),
    ),
]


STRUCTURAL_EDITORIAL_SEEDS = [
    RelationSeed(
        resp_id(47, 1),
        question_id(47),
        "corresponds_to",
        "taxonomy.prudence_core",
        "structural_editorial",
        0.9,
        "Q47 forms the core doctrinal treatment of prudence itself.",
        ("prudence",),
    ),
    RelationSeed(
        resp_id(48, 1),
        question_id(48),
        "corresponds_to",
        "taxonomy.integral_parts_prudence",
        "structural_editorial",
        0.9,
        "Q48 is the tract's organizing article for integral parts.",
        ("integral",),
    ),
    RelationSeed(
        resp_id(48, 1),
        question_id(48),
        "corresponds_to",
        "taxonomy.subjective_parts_prudence",
        "structural_editorial",
        0.9,
        "Q48 is the tract's organizing article for subjective parts.",
        ("subjective",),
    ),
    RelationSeed(
        resp_id(48, 1),
        question_id(48),
        "corresponds_to",
        "taxonomy.potential_parts_prudence",
        "structural_editorial",
        0.9,
        "Q48 is the tract's organizing article for potential parts.",
        ("potential",),
    ),
    RelationSeed(
        resp_id(49, 1),
        question_id(49),
        "corresponds_to",
        "taxonomy.integral_parts_prudence",
        "structural_editorial",
        0.88,
        "Q49 unfolds the integral parts article by article.",
        ("memory",),
    ),
    RelationSeed(
        resp_id(50, 1),
        question_id(50),
        "corresponds_to",
        "taxonomy.subjective_parts_prudence",
        "structural_editorial",
        0.88,
        "Q50 unfolds the subjective parts article by article.",
        ("regnative",),
    ),
    RelationSeed(
        resp_id(51, 1),
        question_id(51),
        "corresponds_to",
        "taxonomy.potential_parts_prudence",
        "structural_editorial",
        0.88,
        "Q51 unfolds the potential parts article by article.",
        ("euboulia",),
    ),
    RelationSeed(
        resp_id(52, 1),
        question_id(52),
        "corresponds_to",
        "taxonomy.gift_of_counsel",
        "structural_editorial",
        0.88,
        "Q52 treats prudence's corresponding gift.",
        ("gift of the Holy Ghost",),
    ),
    RelationSeed(
        resp_id(53, 1),
        question_id(53),
        "corresponds_to",
        "taxonomy.prudence_defects",
        "structural_editorial",
        0.88,
        "Q53 begins the tract on imprudence and allied defects.",
        ("imprudence",),
    ),
    RelationSeed(
        resp_id(54, 1),
        question_id(54),
        "corresponds_to",
        "taxonomy.prudence_defects",
        "structural_editorial",
        0.88,
        "Q54 continues the tract on prudential defects through negligence.",
        ("negligence",),
    ),
    RelationSeed(
        resp_id(55, 1),
        question_id(55),
        "corresponds_to",
        "taxonomy.counterfeit_prudence",
        "structural_editorial",
        0.9,
        "Q55 treats counterfeit or misdirected prudence-like forms.",
        ("prudence of the flesh",),
    ),
    RelationSeed(
        resp_id(56, 1),
        question_id(56),
        "corresponds_to",
        "taxonomy.prudence_precepts",
        "structural_editorial",
        0.88,
        "Q56 gathers the precept material for prudence and its opposite vices.",
        ("precepts",),
    ),
]


CANDIDATE_MENTIONS = [
    {
        "mention_id": "cand-mention-q049-a002-understanding-overlap",
        "source_passage_id": resp_id(49, 2),
        "candidate_concept_id": "candidate.understanding_overlap",
        "candidate_label": "Understanding overlap with other corpus senses",
        "candidate_type": "taxonomy",
        "mention_text": "Understanding denotes here, not the intellectual power, but the right estimate about some final principle",
        "note": "Human review still needed on how aggressively to disambiguate this prudential 'understanding' from the gift of understanding elsewhere in the corpus.",
    },
    {
        "mention_id": "cand-mention-q049-a005-reason-label",
        "source_passage_id": resp_id(49, 5),
        "candidate_concept_id": "candidate.reason_label",
        "candidate_label": "Reason vs Reasoning normalization risk",
        "candidate_type": "taxonomy",
        "mention_text": "it follows that reason should be numbered among these parts",
        "note": "The reviewed registry normalizes this prudence-part as Reasoning, but the source also uses 'reason'. Keep this visible for future review.",
    },
    {
        "mention_id": "cand-mention-q047-a009-solicitude-act",
        "source_passage_id": resp_id(47, 9),
        "candidate_concept_id": "candidate.solicitude_classification",
        "candidate_label": "Solicitude classification",
        "candidate_type": "taxonomy",
        "mention_text": "this belongs to prudence",
        "note": "Further review is needed on whether solicitude should remain a lightweight act node or be folded into richer prudential act modeling later.",
    },
    {
        "mention_id": "cand-mention-q055-a007-future-solicitude-boundary",
        "source_passage_id": resp_id(55, 7),
        "candidate_concept_id": "candidate.future_solicitude_boundary",
        "candidate_label": "Future solicitude boundary case",
        "candidate_type": "taxonomy",
        "mention_text": "every time has its own fitting proper solicitude",
        "note": "Human review is still needed on the boundary between lawful foresight and unlawful future solicitude.",
    },
]


CANDIDATE_RELATION_PROPOSALS = [
    {
        "proposal_id": "cand-rel-q047-a009-prudence-has-act-solicitude",
        "source_passage_id": resp_id(47, 9),
        "subject_id": "concept.prudence",
        "subject_label": "Prudence",
        "relation_type": "has_act",
        "object_id": "concept.solicitude",
        "object_label": "Solicitude",
        "rationale": "There is strong textual support already, but a future review pass may want finer act taxonomy before keeping this edge as fully settled.",
        "confidence": 0.72,
    },
    {
        "proposal_id": "cand-rel-q047-a013-false-prudence-contrary",
        "source_passage_id": resp_id(47, 13),
        "subject_id": "concept.false_prudence",
        "subject_label": "False Prudence",
        "relation_type": "contrary_to",
        "object_id": "concept.prudence",
        "object_label": "Prudence",
        "rationale": "The passage names likeness rather than formal contrariety, so this relation is still held back from reviewed doctrine.",
        "confidence": 0.68,
    },
    {
        "proposal_id": "cand-rel-q055-a006-temporal-solicitude-opposed",
        "source_passage_id": resp_id(55, 6),
        "subject_id": "concept.temporal_solicitude",
        "subject_label": "Solicitude about Temporal Things",
        "relation_type": "opposed_by",
        "object_id": "concept.prudence",
        "object_label": "Prudence",
        "rationale": "The passage frames unlawful temporal solicitude as disordered, but the exact edge family needs further review.",
        "confidence": 0.66,
    },
    {
        "proposal_id": "cand-rel-q055-a007-future-solicitude-opposed",
        "source_passage_id": resp_id(55, 7),
        "subject_id": "concept.future_solicitude",
        "subject_label": "Solicitude about the Future",
        "relation_type": "opposed_by",
        "object_id": "concept.prudence",
        "object_label": "Prudence",
        "rationale": "The tract clearly criticizes excessive future solicitude, but the reviewed layer keeps the stronger negative edge out pending more exact normalization.",
        "confidence": 0.64,
    },
    {
        "proposal_id": "cand-rel-q051-a004-gnome-higher-principles",
        "source_passage_id": resp_id(51, 4),
        "subject_id": "concept.gnome",
        "subject_label": "Gnome",
        "relation_type": "regulated_by",
        "object_id": "concept.prudence",
        "object_label": "Prudence",
        "rationale": "Gnome clearly belongs in the prudential family, but the better reviewed edge may remain potential_part_of rather than a broader regulative relation.",
        "confidence": 0.61,
    },
]
